services:
  web:
    build: .
    restart: always
    command: gunicorn DjangoProject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    networks:
      - backend

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - backend

volumes:
  static_volume:

networks:
  backend:
    driver: bridge
