# Generated by Django 5.1.5 on 2025-04-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_avatar_alter_user_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('svo', 'Боец СВО'), ('volunteer', 'Волонтёр'), ('mentor', 'Наставник'), ('peresel', 'Переселенец'), ('family', 'Семья бойцов'), ('admin', 'Администратор')], default='user', max_length=30),
        ),
    ]
